### ISSUE TITLE
The game music

### ISSUE THREAD

**Issue by venelinpetrov** [LongbowGames/TreadMarks#1]
Do  you preserve any clues of how the music is made, notes, synths patches, samples and stuff like that?

**Comment by leilei-** [comment]
If I had a guess on how it was done, i'd say probably a copy of Acid Pro producing WAV streams way back in 1999.  The final result lived as mono WAVs, then soon later as stereo MP3s, and then Oggs in this incarnation.

**Comment by Skrapion** [comment]
The much was originally MODs, and the game used a licensed audio library to play them. When I made the game cross-platform, I converted the music to OGGs which SFML could play easily. I think I used WinAmp to convert them.

I'm not with Longbow anymore, so my time is limited, but I'll try to remember to see if I can pull down the original MODs and put them in a source directory somewhere.

**Comment by clort81** [comment]
> The much was originally MODs, and the game used a licensed audio library to play them. When I made the game cross-platform, I converted the music to OGGs which SFML could play easily. I think I used WinAmp to convert them.

I found treadmarksdemo.exe here: Does it contain the mods?

 [https://web.archive.org/web/20000816003749/http://www.treadmarks.com/treadmarksdemo.exe](https://web.archive.org/web/20000816003749/http://www.treadmarks.com/treadmarksdemo.exe)

**Comment by Skrapion** [comment]
Actually, I think I was mistaken. DX-Ball 2/Rival Ball had music by Sidewinder, who used MODs, but the Treadmarks music was by Al Ryan, who gave us MP3s.

I couldn't open that archived link, but [this one from 2009](https://web.archive.org/downloads/Tread%20Marks%20Demo%20Install.exe) has two MP3s. The full version came with more music.
